#define ASSIGN                          1
#define BITOR                           2
#define FUNCTION_DEC                    3
#define FUNCTION_CALL                   4
#define INDEX                           5
#define OR                              6
#define AND                             7
#define BITXOR                          8
#define BITAND                          9
#define EQUALTO                        10
#define NOTEQUALTO                     11
#define GREATERTHAN                    12
#define GORE                           13
#define LESSTHAN                       14
#define LORE                           15
#define SHIFTL                         16
#define SHIFTR                         17
#define PLUS                           18
#define MINUS                          19
#define DIVIDE                         20
#define TIMES                          21
#define MODULO                         22
#define POW                            23
#define NOT                            24
#define BITNOT                         25
#define UMINUS                         26
#define PLUSPLUS                       27
#define LPAREN                         28
#define RPAREN                         29
#define COMMA                          30
#define LBRAC                          31
#define RBRAC                          32
#define COLLECTARRAY                   33
#define NEWLINE                        34
#define NAME                           35
#define GUARD_N                        36
#define GUARD_S                        37
#define WILDCARD_N                     38
#define WILDCARD                       39
#define WHERE                          40
#define CASE                           41
#define OF                             42
#define POINTER                        43
#define LET                            44
#define IN                             45
#define OPENBRAC                       46
#define PRINT                          47
#define NUM                            48
#define STRING                         49
#define BOOLEAN                        50
#define OPENQUOTEERROR                 51
