#define ASSIGN                          1
#define BITOR                           2
#define FUNCTION_DEC                    3
#define FUNCTION_CALL                   4
#define INDEX                           5
#define OR                              6
#define AND                             7
#define BITXOR                          8
#define BITAND                          9
#define EQUALTO                        10
#define NOTEQUALTO                     11
#define GREATERTHAN                    12
#define GORE                           13
#define LESSTHAN                       14
#define LORE                           15
#define SHIFTL                         16
#define SHIFTR                         17
#define PLUS                           18
#define MINUS                          19
#define DIVIDE                         20
#define TIMES                          21
#define MODULO                         22
#define POW                            23
#define NOT                            24
#define BITNOT                         25
#define UMINUS                         26
#define PLUSPLUS                       27
#define LPAREN                         28
#define RPAREN                         29
#define COMMA                          30
#define LBRAC                          31
#define RBRAC                          32
#define COLLECTARRAY                   33
#define DELIMITER                      34
#define NAME                           35
#define LCURL                          36
#define RCURL                          37
#define WILDCARD                       38
#define WHERE                          39
#define CASE                           40
#define OF                             41
#define LET                            42
#define IN                             43
#define OPENBRAC                       44
#define PRINT                          45
#define NUM                            46
#define STRING                         47
#define BOOLEAN                        48
#define OPENQUOTEERROR                 49
