#define OR                              1
#define AND                             2
#define BITXOR                          3
#define BITOR                           4
#define BITAND                          5
#define EQUALTO                         6
#define NOTEQUALTO                      7
#define GREATERTHAN                     8
#define GORE                            9
#define LESSTHAN                       10
#define LORE                           11
#define SHIFTL                         12
#define SHIFTR                         13
#define PLUS                           14
#define MINUS                          15
#define DIVIDE                         16
#define TIMES                          17
#define MODULO                         18
#define POW                            19
#define NOT                            20
#define BITNOT                         21
#define UMINUS                         22
#define LPAREN                         23
#define RPAREN                         24
#define COMMA                          25
#define LBRAC                          26
#define RBRAC                          27
#define ASSIGN                         28
#define NEWLINE                        29
#define NUM                            30
#define STRING                         31
